### ISSUE TITLE
Chatsidebar is blank on profile page

### ISSUE THREAD

**Issue by Pranshu1902** [coronasafe/ayushma_fe#128]
https://ayushma.ohc.network/profile
The chat sidebar doesn't list the chats on the profile page because the `project_id` isn't present in the URL. Is that expected behavior or a bug?
![image](https://github.com/coronasafe/ayushma_fe/assets/70687348/433f3f14-7349-4eed-8811-f49a9a1e94a4)

**Comment by Pranshu1902** [comment]
@skks1212 was this an expected behaviour?

**Comment by skks1212** [comment]
@Pranshu1902 yes, this is expected behavior. Sorry for the late reply
