### ISSUE TITLE
Unable to add the same questions in test suite

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/ayushma_fe#147]
When trying to add the same question to the test suite one after the other, the question does not get added unless i clear the input and paste the same question again.

![msedge_EBKe3qsfSi](https://github.com/coronasafe/ayushma_fe/assets/3626859/becfd772-f3be-4baa-b5f7-6eaab1a88a60)

Fix: Clear the question input once the user clicks the add question button.

**Comment by skks1212** [comment]
Adding to the above issue, increase the width of the modal

**Comment by thedevildude** [comment]
@Ashesh3 Can you assign me the issue?

**Comment by Ashesh3** [comment]
@thedevildude unassigning due to inactivity
