### ISSUE TITLE
Fix Thumbs Up/Down popup design 

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/ayushma_fe#162]
Currently the feedback modal is broken and stretches the window when clicked. 

![image](https://github.com/coronasafe/ayushma_fe/assets/3626859/b7df4924-63a5-4217-8fcf-1c8052864afb)

To reproduce, create a new chat, click on thumbs up/down icon next to the ai's response
![image](https://github.com/coronasafe/ayushma_fe/assets/3626859/0688fa3e-f909-422e-8044-598d68cd834c)

**Comment by thedevildude** [comment]
@Ashesh3  Can you assign me this issue?

**Comment by Ashesh3** [comment]
> @Ashesh3 Can you assign me this issue?

assigned
