### ISSUE TITLE
Broken UI in Settings Popup

### ISSUE THREAD

**Issue by gigincg** [coronasafe/ayushma_fe#172]
https://github.com/coronasafe/ayushma/assets/13028584/117698bf-d5d6-4b8c-af67-bc917c3f8e8a

**Comment by skks1212** [comment]
@gigincg I am unable to replicate this on my end.

**Comment by Ashesh3** [comment]
Unable to replicate, closing for now. Feel free to re-open with device configuration details on which the issue occurs.
![image](https://github.com/coronasafe/ayushma_fe/assets/3626859/2cc0c6dc-4b6c-4c1c-b53e-d3bd65a0c6b4)
