### ISSUE TITLE
Improve User Experience by Delaying and Repositioning Interaction Buttons.

### ISSUE THREAD

**Issue by Lobi29** [coronasafe/ayushma_fe#182]
![issue1](https://github.com/coronasafe/ayushma_fe/assets/108052802/06553cf7-212e-475a-a627-7fc473bfb620)

<h1 align="center">ISSUE</h1>

- Currently, users can interact with these buttons while the bot is still generating the answer, which might lead to distractions and premature judgments. I suggest delaying the appearance of these buttons until the answer is complete for a smoother user experience.

- Additionally, positioning them closer to the answer would enhance accessibility and engagement.

**Comment by skks1212** [comment]
@Lobi29 I have assigned this issue to you. If you do not wish to take it, feel free to unassign yourself

**Comment by Lobi29** [comment]
I am happy to work on it, thank you for assigning this issue to me 🚀
