### ISSUE TITLE
Clean chatbot code and references

### ISSUE THREAD

**Issue by skks1212** [coronasafe/ayushma_fe#183]
`/chatbot` was added for experimentation but is no longer needed. Remove all files for the same aswell as scripts in package.json. All other references need to be cleaned.

**Comment by vishisht-dubey** [comment]
hey @skks1212 i am doing this assign this to me i will raise the pr by today

**Comment by skks1212** [comment]
@vishisht-dubey issue assigned!

**Comment by vishisht-dubey** [comment]
hey @skks1212 i have raised the pr [https://github.com/coronasafe/ayushma_fe/pull/189](#183) please review the pr and merge it

**Comment by vishisht-dubey** [comment]
@skks1212 any update??
