### ISSUE TITLE
Add Support for Bulk Question Import via CSV in Automated Test Suite

### ISSUE THREAD

**Issue by Ashesh3** [coronasafe/ayushma_fe#186]
#### Summary:
Our AI project, Ayushma, currently relies on a manual process for entering questions into our automated test suite. This approach is increasingly cumbersome and inefficient, especially as we scale up our testing with larger datasets. To streamline this process, we propose the implementation of a feature that allows for the bulk import of questions via a CSV file.

#### Feature Request:
**Automated Question Import via CSV**

#### Description:
The automated test suite should be enhanced to support the import of questions in bulk from a CSV file. This feature would significantly reduce the time and effort required to populate the test suite with a large number of questions, facilitating more efficient testing cycles and allowing for a broader range of tests to be conducted in a shorter time frame.

#### Proposed CSV Format:
The CSV file should adhere to the following format for each entry:
```
question, human_answer, language_code
```
- **question**: The question text to be tested.
- **human_answer**: The expected answer or response that a human would provide.
- **language_code**: The ISO language code representing the language of the question and answer (e.g., `en` for English).

#### Implementation Details:
- The test suite should include a function or interface for importing questions from a CSV file.
- Upon import, the suite should parse the CSV file and add each question to the testing queue, along with its corresponding human-provided answer and language code.
- The feature should support error handling for improperly formatted CSV files and provide meaningful feedback to the user on any corrections needed.

We believe that implementing this feature will be a substantial step forward in enhancing our AI project's testing capabilities and overall efficiency. We look forward to the community's feedback and contributions to this proposal.

**Comment by vishisht-dubey** [comment]
Hi @Ashesh3 i would like to work on this, would you please assign this to me
also i am trying to contribute to GSOC so let me know the further details of contributing to this org.

**Comment by Ashesh3** [comment]
Hey @vishisht-dubey , Welcome! For more information regarding our project and GSOC join our slack and check out the announcement channel! You can also ask any doubts or clarifications there.

**Comment by vishisht-dubey** [comment]
so @Ashesh3 i would get a csv which contains 3 headers question, human_answer, language_code, now the task is to develop a function which would take question, human_answer and language_code and map all those for all the entres so that we dont need to manually add data in test suite

**Comment by Ashesh3** [comment]
Yep, currently we do have an option to manually add a question, look at that API endpoint from the code. You need to make a feature where a user can click "Import questions" and provide a CSV file. Then you'd just loop through all the rows and call that API endpoint multiple times, which will add all the questions one by one.

**Comment by Ashesh3** [comment]
@vishisht-dubey

**Comment by vishisht-dubey** [comment]
@Ashesh3  can you tell me the path where we enter questions for test suite

**Comment by vishisht-dubey** [comment]
> @Ashesh3 can you tell me the path where we enter questions for test suite

is it src/app/admin/tests

**Comment by vishisht-dubey** [comment]
just a query that while i am adding the question post request is not responding and !storage?.user?.is_staff since this is false i am unable to access some things can you guide me a little how to test apis and everything should work?
![Screenshot 2024-02-28 235953](https://github.com/coronasafe/ayushma_fe/assets/98794736/724add19-65b1-4ce1-a50a-caa24324609d)

**Comment by vishisht-dubey** [comment]
@Ashesh3 yes please host the backend and provide the staff account access as i also need to check on the frontend part whether its working or not

**Comment by vishisht-dubey** [comment]
Hiiii @Ashesh3 i have completed the logic part, please host the backend so that i can test it.
What happens if there is some error while uploading the question? does handle add question throws any error or any confirmation that the data is successfully uploaded??

**Comment by Ashesh3** [comment]
Hey @vishisht-dubey I'll host the backend for you by tonight.
User should be clearly made aware of any errors while importing, show the error but skip that question and continue import.

**Comment by Ashesh3** [comment]
@vishisht-dubey Backend is hosted here `https://ayushma.ashsec.us.to` , Update the same in your .env file following the existing format

**Comment by vishisht-dubey** [comment]
hey @Ashesh3  i am unable to login using dummy email do i need to use some other email ??

**Comment by Ashesh3** [comment]
> hey @Ashesh3 i am unable to login using dummy email do i need to use some other email ??

Try this:
```
Email: demo@demo.com
Username: demo
Password: demo
``

**Comment by vishisht-dubey** [comment]
> > hey @Ashesh3 i am unable to login using dummy email do i need to use some other email ??
> 
> You can just create a user by yourself too by visiting the registration page.
> 
> I've created an account for you, try this:
> 
> ```
> Email: admin@admin.com
> Username: admin
> Password: admin
> ```

ok i got it

**Comment by vishisht-dubey** [comment]
Hiii @Ashesh3 
just want a quick review 
I have used react-csv-reader for reading the data from csv 
currently the UI is looking like this
I will change to look more better
![Screenshot 2024-03-04 180626](https://github.com/coronasafe/ayushma_fe/assets/98794736/e9eb3434-a85e-4532-86e0-2e5c5e14f0bf)
So when we click choose file and select a csv if the csv contains headers like question,human_answer,language then only it proceeds with the csv else it says upload correct csv and if the csv is correct it uses handleAddQuestion function in a loop untill all the data from csv is completed. I have also implemented checks in between so if there is a row which does not contains any of the details like question or human_answer or language it simply does not add that data as well this helps in stopping the missing values to enter is this approach correct??? please give suggestions......

**Comment by Ashesh3** [comment]
> Hiii @Ashesh3 just want a quick review I have used react-csv-reader for reading the data from csv currently the UI is looking like this I will change to look more better ![Screenshot 2024-03-04 180626](https://private-user-images.githubusercontent.com/98794736/309755722-e9eb3434-a85e-4532-86e0-2e5c5e14f0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTkyMzcsIm5iZiI6MTcwOTU1ODkzNywicGF0aCI6Ii85ODc5NDczNi8zMDk3NTU3MjItZTllYjM0MzQtYTg1ZS00NTMyLTg2ZTAtMmU1YzVlMTRmMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEzMjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMDMzNDgzNzk2MTY3MWFlMTcwODdlY2NmNjI3YjY0YTNlYjgyMTU5YjljOTk4YTU5YTNkOTA4YzBmMGNlNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lObAoWVq9kRrCI0thtTO6xfw840JcNJB-B6U_PcyeXE) So when we click choose file and select a csv if the csv contains headers like question,human_answer,language then only it proceeds with the csv else it says upload correct csv and if the csv is correct it uses handleAddQuestion function in a loop untill all the data from csv is completed. I have also implemented checks in between so if there is a row which does not contains any of the details like question or human_answer or language it simply does not add that data as well this helps in stopping the missing values to enter is this approach correct??? please give suggestions......

Approach sounds good, let's get the design ready now!

**Comment by vishisht-dubey** [comment]
> > Hiii @Ashesh3 just want a quick review I have used react-csv-reader for reading the data from csv currently the UI is looking like this I will change to look more better ![Screenshot 2024-03-04 180626](https://private-user-images.githubusercontent.com/98794736/309755722-e9eb3434-a85e-4532-86e0-2e5c5e14f0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTkyMzcsIm5iZiI6MTcwOTU1ODkzNywicGF0aCI6Ii85ODc5NDczNi8zMDk3NTU3MjItZTllYjM0MzQtYTg1ZS00NTMyLTg2ZTAtMmU1YzVlMTRmMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEzMjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMDMzNDgzNzk2MTY3MWFlMTcwODdlY2NmNjI3YjY0YTNlYjgyMTU5YjljOTk4YTU5YTNkOTA4YzBmMGNlNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lObAoWVq9kRrCI0thtTO6xfw840JcNJB-B6U_PcyeXE) So when we click choose file and select a csv if the csv contains headers like question,human_answer,language then only it proceeds with the csv else it says upload correct csv and if the csv is correct it uses handleAddQuestion function in a loop untill all the data from csv is completed. I have also implemented checks in between so if there is a row which does not contains any of the details like question or human_answer or language it simply does not add that data as well this helps in stopping the missing values to enter is this approach correct??? please give suggestions......
> 
> Approach sounds good, let's get the design ready now!

one more query like if the api fails to upload a question, what does it return because while running a loop it may be possible that at some point or due to network, api may get fail so that's why i am asking

**Comment by vishisht-dubey** [comment]
@Ashesh3 can i open a pr so that you can review my code and also check whether the import from csv is working fine or not??

**Comment by Ashesh3** [comment]
> > > Hiii @Ashesh3 just want a quick review I have used react-csv-reader for reading the data from csv currently the UI is looking like this I will change to look more better ![Screenshot 2024-03-04 180626](https://private-user-images.githubusercontent.com/98794736/309755722-e9eb3434-a85e-4532-86e0-2e5c5e14f0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTkyMzcsIm5iZiI6MTcwOTU1ODkzNywicGF0aCI6Ii85ODc5NDczNi8zMDk3NTU3MjItZTllYjM0MzQtYTg1ZS00NTMyLTg2ZTAtMmU1YzVlMTRmMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEzMjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMDMzNDgzNzk2MTY3MWFlMTcwODdlY2NmNjI3YjY0YTNlYjgyMTU5YjljOTk4YTU5YTNkOTA4YzBmMGNlNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lObAoWVq9kRrCI0thtTO6xfw840JcNJB-B6U_PcyeXE) So when we click choose file and select a csv if the csv contains headers like question,human_answer,language then only it proceeds with the csv else it says upload correct csv and if the csv is correct it uses handleAddQuestion function in a loop untill all the data from csv is completed. I have also implemented checks in between so if there is a row which does not contains any of the details like question or human_answer or language it simply does not add that data as well this helps in stopping the missing values to enter is this approach correct??? please give suggestions......
> > 
> > 
> > Approach sounds good, let's get the design ready now!
> 
> one more query like if the api fails to upload a question, what does it return because while running a loop it may be possible that at some point or due to network, api may get fail so that's why i am asking

If any question fails, just display an error that "Question: ... failed to import"

**Comment by Ashesh3** [comment]
> @Ashesh3 can i open a pr so that you can review my code and also check whether the import from csv is working fine or not??

Sure, go ahead.

**Comment by vishisht-dubey** [comment]
Hii @Ashesh3 I have created a pr [#186](https://github.com/coronasafe/ayushma_fe/pull/190) please let me know once you test it.
