### ISSUE TITLE
Add infinite scrolling for chat history

### ISSUE THREAD

**Issue by skks1212** [coronasafe/ayushma_fe#25]
Currently only 10 results are returned by API in the sidebar history
Using react infinite scroll (you will have to install it) and react query's `useInfiniteQuery` make the API fetch previous history as you scroll down.

**Comment by rondDev** [comment]
And how do you imagine pagination is going to work?

**Comment by skks1212** [comment]
@rondDev we use offset pagination in our APIs Sending an offset value will work for us.

**Comment by rondDev** [comment]
The code wasn't exactly descriptive with filters and such and I couldn't find any docs... So it's kinda hard to use an API I know nothing about

**Comment by skks1212** [comment]
@rondDev We are setting up a Readme file containing important information. Until then you can use :

Django Backend : https://github.com/coronasafe/ayushma

Backend hosted at : https://ayushma-api.ohc.network

Let me know if you are looking out for more info.

**Comment by thedevildude** [comment]
Solved on PR 74
