### ISSUE TITLE
Add labels to details form in project page

### ISSUE THREAD

**Issue by suprabathk** [coronasafe/ayushma_fe#40]
The details form is missing labels for fields.
We could also organize the action buttons.

<img width="960" alt="image" src="https://github.com/coronasafe/ayushma_fe/assets/34211797/cb33a972-1000-4e41-90a6-1a4b06264f48">

**Comment by siddnikh** [comment]
As discussed with @skks1212 labels seem unnecessary. Placeholders are fine for the time being.
