### ISSUE TITLE
Show an error when the /converse API fails

### ISSUE THREAD

**Issue by suprabathk** [coronasafe/ayushma_fe#71]
**WHAT:**
An error should be shown if the /converse api fails during chatting.
Currently, the chat will stay in loading state infinitely when an error occurs.

<img width="960" alt="image" src="https://github.com/coronasafe/ayushma_fe/assets/34211797/a54e848e-dd6f-43f6-aa86-70ebd899865a">

**Comment by thedevildude** [comment]
Hi, is this issue being worked upon?
