### ISSUE TITLE
Chat search triggers a get request every time input changes

### ISSUE THREAD

**Issue by skks1212** [coronasafe/ayushma_fe#75]
Chat search should only trigger after the user has stopped typing, preferably for 1 second. Also, add horizontal padding to the chats list and customize the scrollbar to take up less width.

![image](https://github.com/coronasafe/ayushma_fe/assets/23238460/4826a12e-04e9-46b4-a2c1-35979e1fec84)

**Comment by thedevildude** [comment]
Hi, can you please assign it to me
