### ISSUE TITLE
Add documentation for env variables

### ISSUE THREAD

**Issue by skks1212** [coronasafe/ayushma_fe#83]
Update the readme file to include documentation for all env variables required to be setup to deploy ayushma. Something similar as implemented in the backend repo

**Comment by varunsh17** [comment]
Happy to work and I have also gone through the necessary information required to get started. Please assign the issue to me so that I can get started

**Comment by skks1212** [comment]
@varunsh17 seems like the env variables have already been added in a recent commit. Do keep looking out for other issues to take up!
