### ISSUE TITLE
Add env variables to configure logos

### ISSUE THREAD

**Issue by skks1212** [coronasafe/ayushma_fe#86]
Add variables

NEXT_PUBLIC_LOGO_URL

these will be optional, and if present, will override the current logo. (they should be urls)
Update the admin panel to use the same logo

![image](https://github.com/coronasafe/ayushma_fe/assets/23238460/44adfadd-8670-4f67-b916-6a9cae7d94ba)

**Comment by bodhish** [comment]
@skks1212 Let's have 1 logo; For admin lets not take another logo;

**Comment by suprabathk** [comment]
I would like to work on this
