### ISSUE TITLE
List chats in descending order of creation

### ISSUE THREAD

**Issue by skks1212** [coronasafe/ayushma_fe#89]
![image](https://github.com/coronasafe/ayushma_fe/assets/23238460/25670acf-fd2a-44d6-a07b-c0633d99882c)

**Comment by suprabathk** [comment]
I would like to take this up

**Comment by suprabathk** [comment]
Fixed in BE: [https://github.com/coronasafe/ayushma/pull/279](https://github.com/coronasafe/ayushma/pull/279)
