### ISSUE TITLE
Update project page metadata to change page title and description according to project

### ISSUE THREAD

**Issue by skks1212** [coronasafe/ayushma_fe#90]
On chat page, the title should change to the project title
![image](https://github.com/coronasafe/ayushma_fe/assets/23238460/22a06637-9c7a-4de0-8866-6dc3e0c33111)

**Comment by yogeshbhutkar** [comment]
Hey Shivank, can I take this up?

**Comment by yogeshbhutkar** [comment]
Can you close this issue, @skks1212?
